/**
 * Post-process the .docx produced by Pandoc so Word accepts our drawings.
 *
 * Two corrections are applied to `word/document.xml`:
 *
 *  1. **Extended namespace declarations on the root.** Pandoc does not declare
 *     `wpc`/`wpg`/`wps` on `w:document`. Our translator declares them inline on
 *     the elements that use them, which is valid XML but is not what Word
 *     emits, and Word resolves the markup-compatibility (`mc`) processing model
 *     against the *root* declarations. Word itself always declares them on the
 *     root, so we match that.
 *
 *  2. **Document-wide unique drawing ids.** Word treats `wp:docPr/@id` and every
 *     `cNvPr/@id` as one id space per document and reports the file as corrupt
 *     when two collide. The translator is a pure function that numbers each
 *     fragment from 1 independently, so a document with two diagrams (or one
 *     diagram plus a Pandoc-inserted image) always collides until they are
 *     renumbered here — the one place that sees the whole document.
 *
 * Security (AGENTS.md):
 *   * Rule #7 ("don't touch .docx ZIP internals") is deliberately relaxed here:
 *     this replaces exactly one entry (`word/document.xml`) in the archive
 *     Pandoc produced — it is not a reimplementation of ZIP/docx packaging. It
 *     is required for the output to be Word-conformant.
 *   * No external relationship is added (rule #3) and no user-controlled text is
 *     interpolated: the edits are namespace declarations on the root tag and
 *     rewrites of numeric `id` attributes.
 *   * The rewrites are regex-scoped to `id="<digits>"` on a fixed list of
 *     element names. A full XML parser would be sturdier but would mean a new
 *     dependency (rule #6); the input here is machine-generated by Pandoc and by
 *     our own translator, not arbitrary XML.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

/** Extended namespaces Word declares on the document root, prefix -> URI. */
const EXTENDED_NS = {
  'xmlns:wpc': 'http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas',
  'xmlns:mc': 'http://schemas.openxmlformats.org/markup-compatibility/2006',
  'xmlns:wp14': 'http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing',
  'xmlns:wpg': 'http://schemas.microsoft.com/office/word/2010/wordprocessingGroup',
  'xmlns:wps': 'http://schemas.microsoft.com/office/word/2010/wordprocessingShape',
};

/**
 * Prefixes listed in `mc:Ignorable` — the extensions Word may safely skip.
 * `wpc`/`wpg`/`wps` are deliberately absent: they carry the diagram itself, so
 * declaring them ignorable would licence Word to drop it.
 */
const IGNORABLE = 'w14 w15 w16se w16cid w16 w16cex w16sdtdh w16sdtfl w16du wp14';

/** Elements whose `id` attribute *defines* a drawing object id. */
const ID_DEFINING_ELEMENTS = ['wp:docPr', 'wpg:cNvPr', 'wps:cNvPr', 'pic:cNvPr'];

/** Elements whose `id` attribute *references* a drawing object id. */
const ID_REFERENCING_ELEMENTS = ['a:stCxn', 'a:endCxn'];

/**
 * Inject the extended namespace declarations onto the root `w:document`
 * element. Returns the modified XML.
 *
 * The check is scoped to the root's opening tag: the document body legitimately
 * contains inline `xmlns:wpg=` declarations on the drawing elements, so a
 * whole-document search would conclude the namespaces are already present and
 * silently leave the root untouched.
 */
export function injectNamespaces(documentXml) {
  const rootStart = documentXml.indexOf('<w:document');
  if (rootStart < 0) {
    throw new Error('md2nativedocx: could not find <w:document> root element');
  }
  const tagEnd = documentXml.indexOf('>', rootStart);
  if (tagEnd < 0) {
    throw new Error('md2nativedocx: malformed <w:document> root element');
  }
  const openTag = documentXml.slice(rootStart, tagEnd + 1);

  const additions = Object.entries(EXTENDED_NS)
    .filter(([attr]) => !openTag.includes(`${attr}=`))
    .map(([attr, uri]) => ` ${attr}="${uri}"`)
    .join('');
  const ignorable = openTag.includes('mc:Ignorable=') ? '' : ` mc:Ignorable="${IGNORABLE}"`;
  if (!additions && !ignorable) return documentXml;

  const newOpenTag = `${openTag.slice(0, -1)}${additions}${ignorable}>`;
  return documentXml.slice(0, rootStart) + newOpenTag + documentXml.slice(tagEnd + 1);
}

/**
 * Renumber every drawing object id in the document so no two collide.
 *
 * Ids are remapped per `w:drawing` block, because `a:stCxn`/`a:endCxn` reference
 * shapes within their own drawing: a block-local old -> new map keeps each
 * connector attached to the same pair of shapes while a counter shared across
 * blocks guarantees document-wide uniqueness.
 */
export function renumberDrawingIds(documentXml) {
  let nextId = 1;
  const defPattern = new RegExp(`<(${ID_DEFINING_ELEMENTS.join('|')})\\s+id="(\\d+)"`, 'g');
  const refPattern = new RegExp(`<(${ID_REFERENCING_ELEMENTS.join('|')})\\s+id="(\\d+)"`, 'g');

  return documentXml.replace(/<w:drawing>[\s\S]*?<\/w:drawing>/g, (block) => {
    // Pass 1: assign a fresh id to each definition in this drawing.
    const remap = new Map();
    for (const match of block.matchAll(defPattern)) {
      const oldId = match[2];
      if (!remap.has(oldId)) remap.set(oldId, String(nextId++));
    }
    if (remap.size === 0) return block;

    // Pass 2: rewrite definitions and the connector references that point at
    // them. An unmapped reference is left alone rather than guessed at.
    return block
      .replace(defPattern, (whole, tag, oldId) => `<${tag} id="${remap.get(oldId)}"`)
      .replace(refPattern, (whole, tag, oldId) =>
        remap.has(oldId) ? `<${tag} id="${remap.get(oldId)}"` : whole,
      );
  });
}

/**
 * Post-process a .docx file in place: read `word/document.xml`, apply the
 * corrections above, and write the entry back into the archive.
 *
 * @param docxPath - Path to the .docx to patch.
 */
export function postProcessDocx(docxPath) {
  const archive = resolve(docxPath);
  const dir = mkdtempSync(join(tmpdir(), 'md2nativedocx-post-'));
  try {
    // Extract only the part we touch, preserving its path inside the archive so
    // `zip` puts it back exactly where it came from.
    execFileSync('unzip', ['-o', '-q', archive, 'word/document.xml', '-d', dir], { stdio: 'pipe' });
    const entryPath = join(dir, 'word', 'document.xml');
    const original = readFileSync(entryPath, 'utf8');
    const patched = renumberDrawingIds(injectNamespaces(original));
    if (patched === original) return;
    writeFileSync(entryPath, patched, 'utf8');
    // Replace that single entry; every other part of Pandoc's archive is left
    // byte-for-byte untouched.
    execFileSync('zip', ['-q', '-X', archive, 'word/document.xml'], { cwd: dir, stdio: 'pipe' });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}
