/**
 * Post-process the .docx produced by Pandoc so Word accepts our drawings.
 *
 * Two corrections are applied to `word/document.xml`:
 *
 *  1. **Extended namespace declarations on the root.** Pandoc does not declare
 *     `wpc`/`wpg`/`wps` on `w:document`. Our translator declares them inline on
 *     the elements that use them, which is valid XML but is not what Word
 *     emits, and Word resolves the markup-compatibility (`mc`) processing model
 *     against the *root* declarations. Word itself always declares them on the
 *     root, so we match that.
 *
 *  2. **Document-wide unique drawing ids.** Word treats `wp:docPr/@id` and every
 *     `cNvPr/@id` as one id space per document and reports the file as corrupt
 *     when two collide. The translator is a pure function that numbers each
 *     fragment from 1 independently, so a document with two diagrams (or one
 *     diagram plus a Pandoc-inserted image) always collides until they are
 *     renumbered here — the one place that sees the whole document.
 *
 * Security (AGENTS.md):
 *   * Rule #7 ("don't touch .docx ZIP internals") is deliberately relaxed here:
 *     this replaces exactly one entry (`word/document.xml`) in the archive
 *     Pandoc produced — it is not a reimplementation of ZIP/docx packaging. It
 *     is required for the output to be Word-conformant.
 *   * No external relationship is added (rule #3) and no user-controlled text is
 *     interpolated: the edits are namespace declarations on the root tag and
 *     rewrites of numeric `id` attributes.
 *   * The rewrites are regex-scoped to `id="<digits>"` on a fixed list of
 *     element names. A full XML parser would be sturdier but would mean a new
 *     dependency (rule #6); the input here is machine-generated by Pandoc and by
 *     our own translator, not arbitrary XML.
 *
 * A third function, {@link injectSmartArtParts}, goes further than the two
 * corrections above — it adds brand-new ZIP entries (`word/diagrams/*.xml`),
 * not just same-path replacements. Flagged and signed off on separately
 * (`FUTURE_mmd2smartart_SPEC.md` §8, confirmed with the maintainer
 * 2026-09-03) since it's a materially bigger relaxation of rule #7 than the
 * two corrections above. See its own doc comment for why it exists and what
 * it does; it is a no-op whenever a document has no SmartArt diagram in it.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync, existsSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, dirname } from 'node:path';

/** Extended namespaces Word declares on the document root, prefix -> URI. */
const EXTENDED_NS = {
  'xmlns:wpc': 'http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas',
  'xmlns:mc': 'http://schemas.openxmlformats.org/markup-compatibility/2006',
  'xmlns:wp14': 'http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing',
  'xmlns:wpg': 'http://schemas.microsoft.com/office/word/2010/wordprocessingGroup',
  'xmlns:wps': 'http://schemas.microsoft.com/office/word/2010/wordprocessingShape',
};

/**
 * Prefixes listed in `mc:Ignorable` — the extensions Word may safely skip.
 * `wpc`/`wpg`/`wps` are deliberately absent: they carry the diagram itself, so
 * declaring them ignorable would licence Word to drop it.
 *
 * Every prefix listed here MUST also be declared via `xmlns:` on the root
 * (`EXTENDED_NS` above, or Pandoc's own declarations) — the markup-compatibility
 * spec (ECMA-376 Part 3) requires an `mc:Ignorable` prefix to resolve to an
 * in-scope namespace. This used to list the full boilerplate a real Word
 * document advertises (`w14 w15 w16se w16cid w16 w16cex w16sdtdh w16sdtfl
 * w16du wp14`), copied from a real Word document's root without also copying
 * the xmlns declarations those extra prefixes need — nine undeclared
 * prefixes, invalid per spec. Word's parser enforces this strictly and
 * reports the file as needing repair; LibreOffice does not, which is why this
 * went unnoticed through every LibreOffice-headless and structural-XML check
 * (found 2026-09-02, opening a generated .docx in real Word for the first
 * time). `wp14` is the only one of that list we actually declare.
 */
const IGNORABLE = 'wp14';

/** Elements whose `id` attribute *defines* a drawing object id. */
const ID_DEFINING_ELEMENTS = ['wp:docPr', 'wpg:cNvPr', 'wps:cNvPr', 'pic:cNvPr'];

/** Elements whose `id` attribute *references* a drawing object id. */
const ID_REFERENCING_ELEMENTS = ['a:stCxn', 'a:endCxn'];

/**
 * Inject the extended namespace declarations onto the root `w:document`
 * element. Returns the modified XML.
 *
 * The check is scoped to the root's opening tag: the document body legitimately
 * contains inline `xmlns:wpg=` declarations on the drawing elements, so a
 * whole-document search would conclude the namespaces are already present and
 * silently leave the root untouched.
 */
export function injectNamespaces(documentXml) {
  const rootStart = documentXml.indexOf('<w:document');
  if (rootStart < 0) {
    throw new Error('md2nativedocx: could not find <w:document> root element');
  }
  const tagEnd = documentXml.indexOf('>', rootStart);
  if (tagEnd < 0) {
    throw new Error('md2nativedocx: malformed <w:document> root element');
  }
  const openTag = documentXml.slice(rootStart, tagEnd + 1);

  const additions = Object.entries(EXTENDED_NS)
    .filter(([attr]) => !openTag.includes(`${attr}=`))
    .map(([attr, uri]) => ` ${attr}="${uri}"`)
    .join('');
  const ignorable = openTag.includes('mc:Ignorable=') ? '' : ` mc:Ignorable="${IGNORABLE}"`;
  if (!additions && !ignorable) return documentXml;

  const newOpenTag = `${openTag.slice(0, -1)}${additions}${ignorable}>`;
  return documentXml.slice(0, rootStart) + newOpenTag + documentXml.slice(tagEnd + 1);
}

/**
 * Renumber every drawing object id in the document so no two collide.
 *
 * Ids are remapped per `w:drawing` block, because `a:stCxn`/`a:endCxn` reference
 * shapes within their own drawing: a block-local old -> new map keeps each
 * connector attached to the same pair of shapes while a counter shared across
 * blocks guarantees document-wide uniqueness.
 */
export function renumberDrawingIds(documentXml) {
  let nextId = 1;
  const defPattern = new RegExp(`<(${ID_DEFINING_ELEMENTS.join('|')})\\s+id="(\\d+)"`, 'g');
  const refPattern = new RegExp(`<(${ID_REFERENCING_ELEMENTS.join('|')})\\s+id="(\\d+)"`, 'g');

  return documentXml.replace(/<w:drawing>[\s\S]*?<\/w:drawing>/g, (block) => {
    // Pass 1: assign a fresh id to each definition in this drawing.
    const remap = new Map();
    for (const match of block.matchAll(defPattern)) {
      const oldId = match[2];
      if (!remap.has(oldId)) remap.set(oldId, String(nextId++));
    }
    if (remap.size === 0) return block;

    // Pass 2: rewrite definitions and the connector references that point at
    // them. An unmapped reference is left alone rather than guessed at.
    return block
      .replace(defPattern, (whole, tag, oldId) => `<${tag} id="${remap.get(oldId)}"`)
      .replace(refPattern, (whole, tag, oldId) =>
        remap.has(oldId) ? `<${tag} id="${remap.get(oldId)}"` : whole,
      );
  });
}

/**
 * Post-process a .docx file in place: read `word/document.xml`, apply the
 * corrections above, and write the entry back into the archive.
 *
 * @param docxPath - Path to the .docx to patch.
 */
export function postProcessDocx(docxPath) {
  const archive = resolve(docxPath);
  const dir = mkdtempSync(join(tmpdir(), 'md2nativedocx-post-'));
  try {
    // Extract only the part we touch, preserving its path inside the archive so
    // `zip` puts it back exactly where it came from.
    execFileSync('unzip', ['-o', '-q', archive, 'word/document.xml', '-d', dir], { stdio: 'pipe' });
    const entryPath = join(dir, 'word', 'document.xml');
    const original = readFileSync(entryPath, 'utf8');
    const patched = renumberDrawingIds(injectNamespaces(original));
    if (patched === original) return;
    writeFileSync(entryPath, patched, 'utf8');
    // Replace that single entry; every other part of Pandoc's archive is left
    // byte-for-byte untouched.
    execFileSync('zip', ['-q', '-X', archive, 'word/document.xml'], { cwd: dir, stdio: 'pipe' });
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/**
 * SmartArt package wiring — the "notable postprocess.mjs extension" flagged
 * in `FUTURE_mmd2smartart_SPEC.md` §8 as needing sign-off before writing
 * (given 2026-09-03): adds brand-new ZIP entries, not just a same-path
 * replacement like {@link postProcessDocx} above.
 *
 * Why this exists at all: `packages/pandoc-filter/bin/md2nativedocx-core.mjs`
 * cannot add `.docx` package parts or relationships itself (Pandoc's Lua
 * filter API has no such hook, `FUTURE_mmd2smartart_SPEC.md` §2) — it can
 * only write the *body* XML Pandoc embeds where the ```mermaid block was
 * (`@md2nativedocx/core`'s `buildSmartArtDrawingXml`). So for each SmartArt
 * diagram it instead writes the diagram's 4 XML parts to a temp directory
 * (`smartArtDir`, an env var the CLI sets before invoking Pandoc) under a
 * random id, and embeds placeholder relationship ids
 * (`SMARTART_PLACEHOLDER:<id>:dm` etc.) in `r:dm`/`r:lo`/`r:qs`/`r:cs` —
 * never valid Word relationship ids, just a correlation key. This function
 * is the package-aware step that runs after Pandoc has produced the whole
 * `.docx`: it finds those placeholders, mints real `rId`s, writes the real
 * parts into `word/diagrams/`, and wires up `[Content_Types].xml` +
 * `word/_rels/document.xml.rels` to match — completing exactly the same 4
 * relationships/parts a real Word-authored SmartArt diagram would have
 * (spec §3).
 */
// The id is whatever the core bridge chose (randomUUID() in production, so
// hex+dashes in practice) -- matched as "anything but the ':' delimiter"
// rather than assuming that specific alphabet, so this isn't silently
// fragile against a different id scheme later.
const SMARTART_PLACEHOLDER_RE = /SMARTART_PLACEHOLDER:([^:]+):(dm|lo|qs|cs)/g;

const SMARTART_RELTYPE = {
  dm: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramData',
  lo: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramLayout',
  qs: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramQuickStyle',
  cs: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramColors',
};
const SMARTART_CONTENTTYPE = {
  dm: 'application/vnd.openxmlformats-officedocument.drawingml.diagramData+xml',
  lo: 'application/vnd.openxmlformats-officedocument.drawingml.diagramLayout+xml',
  qs: 'application/vnd.openxmlformats-officedocument.drawingml.diagramStyle+xml',
  cs: 'application/vnd.openxmlformats-officedocument.drawingml.diagramColors+xml',
};
/** `data`/`layout`/`quickStyle`/`colors` — the on-disk part-name stem per kind (`qs` -> `quickStyle1.xml`, not `qs1.xml`). */
const SMARTART_PART_STEM = { dm: 'data', lo: 'layout', qs: 'quickStyle', cs: 'colors' };
/** The 4 files `md2nativedocx-core.mjs` writes per diagram id, one per relIds kind. */
const SMARTART_SOURCE_FILE = { dm: 'data.xml', lo: 'layout.xml', qs: 'quickStyle.xml', cs: 'colors.xml' };

/** Every distinct placeholder diagram id referenced in `documentXml`, in first-seen order. */
function findSmartArtPlaceholderIds(documentXml) {
  const ids = [];
  const seen = new Set();
  for (const match of documentXml.matchAll(SMARTART_PLACEHOLDER_RE)) {
    const id = match[1];
    if (!seen.has(id)) {
      seen.add(id);
      ids.push(id);
    }
  }
  return ids;
}

/** The next unused `word/diagrams/data{N}.xml` number, scanning the archive's existing entries (1 if none). */
function nextSmartArtPartNumber(archive) {
  const listing = execFileSync('unzip', ['-l', archive], { encoding: 'utf8' });
  let max = 0;
  for (const match of listing.matchAll(/word\/diagrams\/data(\d+)\.xml/g)) {
    max = Math.max(max, Number(match[1]));
  }
  return max + 1;
}

/** A relationship `Id` not already present in `relsXml`, built from `prefix` + an incrementing counter. */
function nextFreeRelId(relsXml, prefix) {
  let n = 1;
  while (relsXml.includes(`Id="${prefix}${n}"`)) n += 1;
  return `${prefix}${n}`;
}

/**
 * Complete the SmartArt wiring for every placeholder diagram found in
 * `docxPath`'s `word/document.xml` — a no-op (no extraction, no rezip) if
 * none are present, which covers every export that never dispatched to
 * SmartArt in the first place. Must run after {@link postProcessDocx} (this
 * reads the already-namespace-fixed/id-renumbered `word/document.xml`).
 *
 * @param docxPath - Path to the .docx to patch.
 * @param smartArtDir - The directory `MD2NATIVEDOCX_SMARTART_DIR` pointed
 *   the core bridge at; each placeholder id names a `<smartArtDir>/<id>/`
 *   subdirectory holding that diagram's `data.xml`/`layout.xml`/
 *   `colors.xml`/`quickStyle.xml`.
 */
export function injectSmartArtParts(docxPath, smartArtDir) {
  const archive = resolve(docxPath);
  const dir = mkdtempSync(join(tmpdir(), 'md2nativedocx-smartart-'));
  try {
    execFileSync('unzip', ['-o', '-q', archive, 'word/document.xml', '-d', dir], { stdio: 'pipe' });
    const documentPath = join(dir, 'word', 'document.xml');
    let documentXml = readFileSync(documentPath, 'utf8');

    const ids = findSmartArtPlaceholderIds(documentXml);
    if (ids.length === 0) return;

    if (!smartArtDir) {
      throw new Error(
        'md2nativedocx: document.xml references SmartArt placeholders but no smartArtDir was given'
      );
    }

    // unzip treats `[...]` in a member-name argument as a glob character
    // class (not a literal bracket), so `[Content_Types].xml` must be
    // escaped or it silently fails to match ("filename not matched") --
    // found running this end to end, 2026-09-03.
    execFileSync('unzip', ['-o', '-q', archive, '\\[Content_Types\\].xml', 'word/_rels/document.xml.rels', '-d', dir], {
      stdio: 'pipe',
    });
    const contentTypesPath = join(dir, '[Content_Types].xml');
    const relsPath = join(dir, 'word', '_rels', 'document.xml.rels');
    let contentTypes = readFileSync(contentTypesPath, 'utf8');
    let relsXml = readFileSync(relsPath, 'utf8');

    let nextPartNumber = nextSmartArtPartNumber(archive);
    const newEntries = [];

    for (const id of ids) {
      const sourceDir = join(smartArtDir, id);
      if (!existsSync(sourceDir)) {
        throw new Error(`md2nativedocx: no SmartArt parts found for diagram "${id}" in ${smartArtDir}`);
      }

      const n = nextPartNumber++;
      /** @type {Record<'dm'|'lo'|'qs'|'cs', string>} */
      const relIds = {};
      for (const kind of /** @type {const} */ (['dm', 'lo', 'qs', 'cs'])) {
        const partName = `${SMARTART_PART_STEM[kind]}${n}.xml`;
        const partPath = `word/diagrams/${partName}`;
        const xml = readFileSync(join(sourceDir, SMARTART_SOURCE_FILE[kind]), 'utf8');

        const relId = nextFreeRelId(relsXml, `rIdSmartArt${n}${kind.toUpperCase()}`);
        relIds[kind] = relId;
        relsXml = relsXml.replace(
          '</Relationships>',
          `<Relationship Id="${relId}" Type="${SMARTART_RELTYPE[kind]}" Target="diagrams/${partName}" /></Relationships>`
        );
        contentTypes = contentTypes.replace(
          '</Types>',
          `<Override PartName="/${partPath}" ContentType="${SMARTART_CONTENTTYPE[kind]}" /></Types>`
        );

        const diskPath = join(dir, partPath);
        mkdirSync(dirname(diskPath), { recursive: true });
        writeFileSync(diskPath, xml, 'utf8');
        newEntries.push(partPath);
      }

      for (const kind of /** @type {const} */ (['dm', 'lo', 'qs', 'cs'])) {
        documentXml = documentXml.split(`SMARTART_PLACEHOLDER:${id}:${kind}`).join(relIds[kind]);
      }
    }

    // No rule #3 check here (unlike the from-scratch spike scripts this
    // logic descends from): `relsXml` is the *real* document's existing
    // rels file, which may legitimately already contain external
    // relationships Pandoc itself created for Markdown hyperlinks --
    // unrelated to anything this function adds. The 4 relationships added
    // above are always internal (`Target="diagrams/..."`, no `TargetMode`
    // attribute at all), by construction, not by a runtime check.
    writeFileSync(documentPath, documentXml, 'utf8');
    writeFileSync(contentTypesPath, contentTypes, 'utf8');
    writeFileSync(relsPath, relsXml, 'utf8');

    execFileSync(
      'zip',
      ['-q', '-X', archive, 'word/document.xml', '[Content_Types].xml', 'word/_rels/document.xml.rels', ...newEntries],
      { cwd: dir, stdio: 'pipe' }
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}
